version: '3' 

services:
 db:
  image: mariadb:10.4.10
  container_name: nextcloud-mysql
  networks:
  - nextcloud_network
  volumes:
  - /data/nextcloud/mysql:/var/lib/mysql
  - /etc/localtime:/etc/localtime:ro
  environment:
  - MYSQL_ROOT_PASSWORD=123
  - MYSQL_PASSWORD=123
  - MYSQL_DATABASE=nextcloud
  - MYSQL_USER=nextcloud
  restart: unless-stopped
 
 app:
  image: nextcloud:latest
  container_name: nextcloud-app
  networks:
  - nextcloud_network
  depends_on:
  - db
  ports:
  - 8080:80
  volumes:
  - nextcloud:/var/www/html
  - /var/www:/var/www/html/data
  - /etc/localtime:/etc/localtime:ro
  environment:
  - VIRTUAL_HOST=localhost
  - LETSENCRYPT_HOST=localhost
  - LETSENCRYPT_EMAIL=so_dimm@yahoo.com
  restart: unless-stopped

volumes:
 nextcloud:
 db:

networks:
 nextcloud_network:
